### ISSUE TITLE
new plot gap issue

### ISSUE THREAD

**Issue by alexdelli** [SmCTwelve/f1-bot#24]
Hi, after update I have this error, using /plot gap or /plot avg-lap-delta, only on Singapore gp

**command: /plot gap sai lec 2023 15 Race**

2023-09-18 09:39:05,154 f1-bot:     INFO Command: /plot gap in Alexdelli f1-analysis by alexdelli#0
core        WARNING     No lap data for driver 18
core        WARNING     Failed to perform lap accuracy check - all laps marked as inaccurate.
Ignoring exception in on_interaction
Traceback (most recent call last):
  File "/home/container/.local/lib/python3.11/site-packages/discord/commands/core.py", line 124, in wrapped
    ret = await coro(arg)
          ^^^^^^^^^^^^^^^
  File "/home/container/.local/lib/python3.11/site-packages/discord/commands/core.py", line 978, in _invoke
    await self.callback(self.cog, ctx, **kwargs)
  File "/home/container/f1/cogs/plot.py", line 648, in gap
    telemetry = {
                ^
  File "/home/container/f1/cogs/plot.py", line 649, in <dictcomp>
    d: s.laps.pick_drivers(d).pick_fastest().get_car_data(interpolate_edges=True).add_distance()
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/container/.local/lib/python3.11/site-packages/fastf1/core.py", line 2910, in get_car_data
    car_data = self.session.car_data[self['DriverNumber']].slice_by_lap(self, **kwargs).reset_index(drop=True)
               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^
KeyError: nan
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/home/container/.local/lib/python3.11/site-packages/discord/client.py", line 378, in _run_event
    await coro(*args, **kwargs)
  File "/home/container/.local/lib/python3.11/site-packages/discord/bot.py", line 1167, in on_interaction
    await self.process_application_commands(interaction)
  File "/home/container/.local/lib/python3.11/site-packages/discord/bot.py", line 848, in process_application_commands
    await self.invoke_application_command(ctx)
  File "/home/container/.local/lib/python3.11/site-packages/discord/bot.py", line 1118, in invoke_application_command
    await ctx.command.dispatch_error(ctx, exc)
  File "/home/container/.local/lib/python3.11/site-packages/discord/commands/core.py", line 421, in dispatch_error
    await wrapped(ctx, error)
  File "/home/container/.local/lib/python3.11/site-packages/discord/commands/core.py", line 104, in wrapped
    ret = await coro(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/container/f1/cogs/plot.py", line 727, in cog_command_error
    raise error
  File "/home/container/.local/lib/python3.11/site-packages/discord/bot.py", line 1114, in invoke_application_command
    await ctx.command.invoke(ctx)
  File "/home/container/.local/lib/python3.11/site-packages/discord/commands/core.py", line 375, in invoke
    await injected(ctx)
  File "/home/container/.local/lib/python3.11/site-packages/discord/commands/core.py", line 124, in wrapped
    ret = await coro(arg)
          ^^^^^^^^^^^^^^^
  File "/home/container/.local/lib/python3.11/site-packages/discord/commands/core.py", line 1312, in _invoke
    await command.invoke(ctx)
  File "/home/container/.local/lib/python3.11/site-packages/discord/commands/core.py", line 375, in invoke
    await injected(ctx)
  File "/home/container/.local/lib/python3.11/site-packages/discord/commands/core.py", line 132, in wrapped
    raise ApplicationCommandInvokeError(exc) from exc
discord.errors.ApplicationCommandInvokeError: Application Command raised an exception: KeyError: na

**Comment by SmCTwelve** [comment]
Hi,

I'm unable to reproduce the issue with `plot gap` using the same options. Maybe try deleting the cache folder and trying again. It looks to like a FastF1 issue loading the car telemetry, perhaps the data simply wasn't available yet. 

Regarding `plot avg-lap-delta` the data from FastF1 isn't being processed correctly so `session.laps.pick_accurate()` returns empty. This could be a problem with the data from the official live timing API. Only thing I could do to handle that is revert to using unfiltered laps.

**Comment by alexdelli** [comment]
Ok, for plot gap I try to change the Round in Singapore, but not lucky again. 
I copy the new version over the old version (that worked fine), I delete all cache file

2023-09-19 13:32:11,391 f1-bot:     INFO Command: /plot gap in Alexdelli f1-analysis by alexdelli#0
core        WARNING     No lap data for driver 18
core        WARNING     Failed to perform lap accuracy check - all laps marked as inaccurate.
_api        WARNING     Driver 241: Position data is incomplete!
_api        WARNING     Driver 242: Position data is incomplete!
_api        WARNING     Driver 243: Position data is incomplete!
Ignoring exception in on_interaction
Traceback (most recent call last):
  File "/home/container/.local/lib/python3.11/site-packages/discord/commands/core.py", line 124, in wrapped
    ret = await coro(arg)
          ^^^^^^^^^^^^^^^
  File "/home/container/.local/lib/python3.11/site-packages/discord/commands/core.py", line 978, in _invoke
    await self.callback(self.cog, ctx, **kwargs)
  File "/home/container/f1/cogs/plot.py", line 648, in gap
    telemetry = {
                ^
  File "/home/container/f1/cogs/plot.py", line 649, in <dictcomp>
    d: s.laps.pick_drivers(d).pick_fastest().get_car_data(interpolate_edges=True).add_distance()
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/container/.local/lib/python3.11/site-packages/fastf1/core.py", line 2910, in get_car_data
    car_data = self.session.car_data[self['DriverNumber']].slice_by_lap(self, **kwargs).reset_index(drop=True)
               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^
KeyError: nan
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/home/container/.local/lib/python3.11/site-packages/discord/client.py", line 378, in _run_event
    await coro(*args, **kwargs)
  File "/home/container/.local/lib/python3.11/site-packages/discord/bot.py", line 1167, in on_interaction
    await self.process_application_commands(interaction)
  File "/home/container/.local/lib/python3.11/site-packages/discord/bot.py", line 848, in process_application_commands
    await self.invoke_application_command(ctx)
  File "/home/container/.local/lib/python3.11/site-packages/discord/bot.py", line 1118, in invoke_application_command
    await ctx.command.dispatch_error(ctx, exc)
  File "/home/container/.local/lib/python3.11/site-packages/discord/commands/core.py", line 421, in dispatch_error
    await wrapped(ctx, error)
  File "/home/container/.local/lib/python3.11/site-packages/discord/commands/core.py", line 104, in wrapped
    ret = await coro(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/container/f1/cogs/plot.py", line 727, in cog_command_error
    raise error
  File "/home/container/.local/lib/python3.11/site-packages/discord/bot.py", line 1114, in invoke_application_command
    await ctx.command.invoke(ctx)
  File "/home/container/.local/lib/python3.11/site-packages/discord/commands/core.py", line 375, in invoke
    await injected(ctx)
  File "/home/container/.local/lib/python3.11/site-packages/discord/commands/core.py", line 124, in wrapped
    ret = await coro(arg)
          ^^^^^^^^^^^^^^^
  File "/home/container/.local/lib/python3.11/site-packages/discord/commands/core.py", line 1312, in _invoke
    await command.invoke(ctx)
  File "/home/container/.local/lib/python3.11/site-packages/discord/commands/core.py", line 375, in invoke
    await injected(ctx)
  File "/home/container/.local/lib/python3.11/site-packages/discord/commands/core.py", line 132, in wrapped
    raise ApplicationCommandInvokeError(exc) from exc
discord.errors.ApplicationCommandInvokeError: Application Command raised an exception: KeyError: nan

**Comment by alexdelli** [comment]
ooooooh, "nan" could be related to this issue open in fast-f1 yesterday?

https://github.com/theOehrly/Fast-F1/issues/447#issue-1901670682

**Comment by SmCTwelve** [comment]
Yeah I saw that issue, it's probably also related to the FastF1 failed accuracy check. 

I do get this error when using Stroll as one of the drivers but in your original post you were comparing SAI and LEC. For me `plot gap` works with all drivers except Stroll because obviously he has no data. Am I understanding correctly that you are getting this error for any driver or just Stroll?

**Comment by alexdelli** [comment]
> Yeah I saw that issue, it's probably also related to the FastF1 failed accuracy check.
> 
> I do get this error when using Stroll as one of the drivers but in your original post you were comparing SAI and LEC. For me `plot gap` works with all drivers except Stroll because obviously he has no data. Am I understanding correctly that you are getting this error for any driver or just Stroll?

yes, due to cached data.... because I use on ly Sainz and Lec, and other circuits.... :(

**Comment by SmCTwelve** [comment]
I'm really struggling to see why this isn't working for you with any other drivers. 

Here is my result for SAI and LEC. I ran it from a new docker container with a newly built cache. 

![](https://i.imgur.com/hyXGORF.png)

The Stroll DNS shouldn't cause the NaN error unless he is one of the drivers being compared. You are using the latest v2.0.2 release and you updated the dependencies after? And you are running the bot through the Poetry virtual environment or a container? My only other suggestion here is to try completely reinstall, somehow the data or one of your dependencies is different.

**Comment by alexdelli** [comment]
I'm on the usual error every new bot instal.: but it is my faoult, I can't remember how I solved last time

ImportError: cannot import name 'ApplicationContext' from 'discord' (/home/container/.local/lib/python3.11/site-packages/discord/__init__.p

I have to solve this before. I'm using sparkedhost.us
